name: Acorn CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Acorn CLI
        run: npm install -g @acornprover/cli

      - name: Run Acorn
        run: acorn
